### ISSUE TITLE
Exception: Not a packet

### ISSUE THREAD

**Issue by a1147211355** [LionNatsu/hilldust#1]
Traceback (most recent call last):
  File "./hilldust.py", line 28, in <module>
    c.wait_network()
  File "/home/uinnova/hilldust/hillstone.py", line 252, in wait_network
    msg_id, res, _ = Unpack(self.socket.recv(4096))
  File "/home/uinnova/hilldust/hillstone.py", line 145, in Unpack
    if magic != 0x22: raise Exception('Not a packet')
please help me, thanks!

**Comment by LionNatsu** [comment]
It means program received a packet in early stage and the packet did't seem to be a packet in Hillstone protocol. Probably your gateway is using a newer or older protocol.

My university dropped Hillstone gateway so I don't have a test environment. But I notice there is a fork (https://github.com/puppywang/hilldust) days ago did some fixes on protocol  here https://github.com/puppywang/hilldust/commit/30c32794fae31a62d1dcc6abe54fbf643410ba0d. Would you please try that branch and report if it work properly?

**Comment by LionNatsu** [comment]
CC @puppywang

**Comment by a1147211355** [comment]
> It means program received a packet in early stage and the packet did't seem to be a packet in Hillstone protocol. Probably your gateway is using a newer or older protocol.
> 
> My university dropped Hillstone gateway so I don't have a test environment. But I notice there is a fork (https://github.com/puppywang/hilldust) days ago did some fixes on protocol here [puppywang@30c3279](https://github.com/puppywang/hilldust/commit/30c32794fae31a62d1dcc6abe54fbf643410ba0d). Would you please try that branch and report if it work properly?

Sorry, it can be configured, but still can't connect to company-internal network,when i exit it and try it again, error occurred near c.wait_network().
My operating system is Ubuntu 18.10.

**Comment by puppywang** [comment]
You can try my folk version, I used it to connect VPN gateway of my company successfully. If you have any problem, you can show me your log and I will try to fix it.
