### ISSUE TITLE
连接成功后只能访问ip不能访问域名

### ISSUE THREAD

**Issue by ZhangYunP** [LionNatsu/hilldust#5]
dns解析是不是有问题，大神能不能解决下

**Comment by LionNatsu** [comment]
我学校三年前已经不再使用这个品牌的 VPN，没有测试调试环境，实在不好意思。最好能提供更多细节，有助于定位原因。

可以描述一下连接成功后的细节吗？比如连接之后的 /etc/resolv.conf 的内容是什么，程序有没有按照预期修改成 VPN 的 DNS？

另外，在 `platform_linux.py` 的 `def set_network(c:hillstone.ClientCore)` 函数负责实际配置网络参数，可以在里面任意一个地方用 `print(...)` 打印一下 `c.dns_ipv4` `c.gateway_ipv4` 之类的值出来，或许对查明原因有所帮助。

如果你发现了具体哪里不对劲、可能的原因乃至修复方案，都欢迎在此反馈。

**Comment by LionNatsu** [comment]
长时间没有反馈，暂时关闭。如果有更多的线索欢迎重开 issue。
